export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    '1001': 'The question tag is existed in system',
    'ADD': 'Add',
    'ADD_ANSWERS': 'Add answers',
    'ADD_QUESTION_TAG_TITLE': 'Add question tag',
    'ANSWERS': 'Answers',
    'BUTTON_CANCEL': 'Cancel',
    'BUTTON_OK': 'OK',
    'BUTTON_CLOSE': 'Close',
    'BUTTON_SAVE': 'Save',
    'CONFIRMATION': 'Confirmation',
    'CONTENT': 'Content',
    'CREATE_QUESTION_TITLE': 'Create question',
    'DESCRIPTION': 'Description',
    'DIFFICULT_LEVEL': 'Difficult level',
    'EDIT_QUESTION_TAG_TITLE': 'Edit question tag',
    'EDIT_QUESTION_TITLE': 'Edit question',
    'EMAIL': 'Email',
    'ENUM_QUESTION_TYPES_MULTIPLE_CHOICES': 'Multiple choices',
    'ENUM_QUESTION_TYPES_SINGLE_CHOICE': 'Single choice',
    'EXAM_MANAGEMENT': 'Exam management',
    'FORGOTTEN_PASSWORD': 'Forgot my password',
    'GROUP': 'Group of class',
    'LOGIN': 'Login',
    'MSG_CONFIRM_DELETEING_QUESTION_TAGS': 'Are you sure want to delete question tags(s)?',
    'NAME': 'Name',
    'NAME_REQUIRED': 'Name is required',
    'OR': 'Or',
    'PASSWORD': 'Password',
    'PLACEHOLDER_SEARCH_QUESTIONS': 'Search questions',
    'PLACEHOLDER_SEARCH_QUESTION_TAGS': 'Search question tags',
    'PLACEHOLDER_SELECT_QUESTION_TAGS': 'No question tag selected',
    'QUESTIONS': 'Questions',
    'QUESTION_ANSWERS': 'Answers (Select a DSS, must have at least on DSS)',
    'QUESTION_GROUP': 'Question groups',
    'QUESTION_LIST': 'Question list',
    'QUESTION_PAPERS': 'Question papers',
    'QUESTION_TAGS': 'Question tags',
    'QUESTION_TAG_LIST': 'Question tag list',
    'QUESTION_TYPE': 'Question type',
    'REGISTER_A_NEW_MEMBERSHIP': 'Register a new membership',
    'REMEMBER_ME': 'Remember me',
    'REMOVE_ANSWER': 'Remove answer',
    'REMOVE_QUESTION': 'Delete question',
    'SAVED': 'Saved',
    'SEARCH': 'Search',
    'SELECT_A_IMAGE': 'Browse image',
    'SELECT_GROUP':'Select group',
    'SIGNIN_USING_FACEBOOK': 'Sign in using facebook',
    'SIGNIN_USING_GOOGLE_PLUS': 'Sign in using Google+',
    'SPECIALIZED':'Specialized',
    'UPDATE': 'Update',
    'UPLOAD': 'Upload'
};