export const LANG_VI_NAME = 'vi';

export const LANG_VI_TRANS = {
    '1001': 'Nhóm câu hỏi đã tồn tại trong hệ thống',
    'ADD': 'Thêm',
    'ADD_ANSWERS': 'Thêm đáp án',
    'ADD_QUESTION_TAG_TITLE': 'Thêm nhóm câu hỏi',
    'ANSWERS': 'Các câu trả lời',
    'BUTTON_CANCEL': 'Hủy',
    'BUTTON_OK': 'Chấp nhận',
    'BUTTON_CLOSE': 'Đóng',
    'BUTTON_SAVE': 'Lưu',
    'CONFIRMATION': 'Xác nhận',
    'CONTENT': 'Nội dung',
    'CREATE_QUESTION_TITLE': 'Nhập câu hỏi',
    'DESCRIPTION': 'Ghi chú',
    'DIFFICULT_LEVEL': 'Độ khó',
    'EDIT_QUESTION_TAG_TITLE': 'Sửa nhóm câu hỏi',
    'EDIT_QUESTION_TITLE': 'Sửa câu hỏi',
    'EMAIL': 'Địa chỉ email',
    'ENUM_QUESTION_TYPES_MULTIPLE_CHOICES': 'Câu hỏi nhiều đáp án',
    'ENUM_QUESTION_TYPES_SINGLE_CHOICE': 'Câu hỏi một đáp án',
    'EXAM_MANAGEMENT': 'Quản lý thi',
    'FORGOTTEN_PASSWORD': 'Quên mật khẩu',
    'LOGIN': 'Đăng nhập',
    'MSG_CONFIRM_DELETEING_QUESTION_TAGS': 'Bạn có chắc muốn xóa loại câu hỏi không?',
    'NAME': 'Tên',
    'NAME_REQUIRED': 'Tên không được để trống',
    'OR': 'Hoặc',
    'PASSWORD': 'Mật khẩu',
    'PLACEHOLDER_SEARCH_QUESTIONS': 'Tìm câu hỏi',
    'PLACEHOLDER_SEARCH_QUESTION_TAGS': 'Tìm loại câu hỏi',
    'PLACEHOLDER_SELECT_QUESTION_TAGS': 'Chưa chọn loại câu hỏi',
    'QUESTIONS': 'Câu hỏi',
    'QUESTION_ANSWERS': 'Các câu trả lời (Check vào đáp án, phải có ít nhất một đáp án)',
    'QUESTION_GROUP': 'Nhóm câu hỏi',
    'QUESTION_LIST': 'Danh sách câu hỏi',
    'QUESTION_PAPERS': 'Đề thi',
    'QUESTION_TAGS': 'Nhóm câu hỏi',
    'QUESTION_TAG_LIST': 'Danh sách nhóm câu hỏi',
    'QUESTION_TYPE': 'Loại câu hỏi',
    'REGISTER_A_NEW_MEMBERSHIP': 'Đăng ký tài khoản mới',
    'REMEMBER_ME': 'Lưu lại cho lần đăng nhập sau',
    'REMOVE_ANSWER': 'Xóa đáp án',
    'REMOVE_QUESTION': 'Xóa câu hỏi',
    'SAVED': 'Đã lưu',
    'SEARCH': 'Tìm',
    'SELECT_A_IMAGE': 'Chọn hình ảnh',
    'SIGNIN_USING_FACEBOOK': 'Đăng nhập bằng tài khoản facebook',
    'SIGNIN_USING_GOOGLE_PLUS': 'Đăng nhập bằng tài khoản Google+',
    'UPDATE': 'Cập nhật',
    'UPLOAD': 'Tải lên'
};