export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'ADD': 'Add',
    'ADD_ANSWERS': 'Add answers',
    'BUTTON_CANCEL': 'Cancel',
    'BUTTON_OK': 'OK',    
    'CONFIRMATION': 'Confirmation',
    'CONTENT': 'Content',
    'CREATE_QUESTION_TITLE': 'Create question',
    'DESCRIPTION': 'Description',
    'EDIT_QUESTION_TAG_TITLE': 'Edit question tag',
    'EDIT_QUESTION_TITLE': 'Edit question',
    'ENUM_QUESTION_TYPES_MULTIPLE_CHOICES': 'Multiple choices',
    'ENUM_QUESTION_TYPES_SINGLE_CHOICE': 'Single choice',
    'EXAM_MANAGEMENT': 'Exam management', 
    'MSG_CONFIRM_DELETEING_QUESTION_TAGS': 'Are you sure want to delete question tags(s)?',
    'NAME': 'Name',           
    'NAME_REQUIRED': 'Name is required',    
    'PLACEHOLDER_SEARCH_QUESTIONS': 'Search questions',
    'PLACEHOLDER_SEARCH_QUESTION_TAGS': 'Search question tags',
    'PLACEHOLDER_SELECT_QUESTION_TAGS': 'No question tag selected',
    'QUESTIONS': 'Questions',
    'QUESTION_ANSWERS': 'Answers (Select a DSS)',
    'QUESTION_GROUP': 'Question groups',
    'QUESTION_LIST': 'Question list',   
    'QUESTION_PAPERS': 'Question papers',      
    'QUESTION_TAGS': 'Question tags',
    'QUESTION_TAG_LIST': 'Question tag list',
    'REMOVE_ANSWER': 'Remove answer',
    'SAVED': 'Saved',    
    'SEARCH': 'Search',    
    'UPDATE': 'Update'
};